### ISSUE TITLE
toSAS() - The number of seconds since 1960-01-01:00:00:00 GMT is greater than it is supposed to be

### ISSUE THREAD

**Issue by JiayongLee** [warnes/SASxport#19]
Hi,

I am testing the following codes and found that result was 3600 instead of 0. 

![image](https://user-images.githubusercontent.com/19420588/92009693-e11c1980-ed16-11ea-8603-a2970ada0ecc.png)

Thanks,
Jiayong

**Comment by warnes** [comment]
Hi Jiayong, 

I'm not able to replicate this using R 4.0.3 and SASxport 1.8.0 (about to be released).

```
> R.version.string
[1] "R version 4.0.3 (2020-10-10)"
> packageVersion("SASxport")
[1] ‘1.7.0’
> zeroDate <- ISOdate(1960, 01, 01, 00, 00, 00, tz="GMT")
> toSAS(zeroDate, format="DATETIME19.")
[1] 0
attr(,"tzone")
[1] "GMT"
attr(,"SASformat")
[1] "DATETIME19."
```

Please install the latest version of `SASxport` and see if the problem remains.  If so, please provided your OS, R version, and package version.
