### ISSUE TITLE
Minimum length for variable could be less than 8

### ISSUE THREAD

**Issue by bobjersey** [warnes/SASxport#6]
I think the minimum length for a character variable can be as low as 1.
This line of code in R/write.xport.R:
   varLen <- max(c(8,nchar(var, "bytes", keepNA=FALSE) ) ) 
prevents this in this section:
            # compute variable length
            if(is.character(var))
              varLen <- max(c(8,nchar(var, "bytes", keepNA=FALSE) ) )
            else
              varLen <- 8

this section could therefore instead be
            if(is.character(var)) {
              varLen <- max(c(1,nchar(var,"bytes")) )
              # if length is NA, means empty, use 1
              if (is.na(nchar(var) )[1] ) {
                varLen <- 1	
              }
            } else {
              varLen <- 8
            }

Do you agree?
p.s. thanks for the package!

**Comment by gwarnes-mdsol** [comment]
The example files in the technical reports use a storage space of 8 characters even if the contents are only 1 character long. To be safe, we mirror this pattern.

**Comment by gwarnes-mdsol** [comment]
Looking a bit more at the SAS documentation, SAS defaults to 8 character length strings if no format length is specified. 

I suppose it would be good to use the SAS format, if provided.  We'd need to check for and deal with the situation where the format is shorter than the observed data length, perhaps by using the observed length and issuing a warning.

**Comment by bobjersey** [comment]
I am working with xpt file submission to the FDA for drug studies. The FDA document says "The allotted length for each column containing character (text) data should be set to the maximum length of the variable used across all datasets ....". There is another paper from the industry (PharmaSUG2016) where they give examples of character column lengths as low as 1. That is why I thought values less than 8 are desired. Please see these two documents:
https://www.fda.gov/downloads/forindustry/datastandards/studydatastandards/ucm384744.pdf
https://www.pharmasug.org/proceedings/2016/SS/PharmaSUG-2016-SS05.pdf
